### ISSUE TITLE
CUDA_HOME variable not set 

### ISSUE THREAD

**Issue by EidosL** [turboderp/exui#38]
The error says I did not have raise OSError('CUDA_HOME environment variable is not set. '

but when I check 
E:\exui>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:30:42_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0

here is the complete log 

Traceback (most recent call last):
  File "E:\exui\server.py", line 11, in <module>
    from backend.models import update_model, load_models, get_model_info, list_models, remove_model, load_model, unload_model, get_loaded_model
  File "E:\exui\backend\models.py", line 5, in <module>
    from exllamav2 import(
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\exllamav2\model.py", line 23, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\exllamav2\config.py", line 2, in <module>
    from exllamav2.fasttensors import STFile
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\exllamav2\fasttensors.py", line 5, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\exllamav2\ext.py", line 153, in <module>
    exllamav2_ext = load \
                    ^^^^^^
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\torch\utils\cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\torch\utils\cpp_extension.py", line 1887, in _prepare_ldflags
    extra_ldflags.append(f'/LIBPATH:{_join_cuda_home("lib", "x64")}')
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LEE\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\torch\utils\cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

E:\exui>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:30:42_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0

**Comment by ElfrinoGem** [comment]
I'm getting the same error.

**Comment by dsent** [comment]
I get the same error, despite having installed precompiled versions of torch and exllamav2, as per the [instruction](https://github.com/turboderp/exui/blob/master/doc/manual-install.md).

**Comment by zero-stroke** [comment]
I was able to fix this with this in an admin cmd:
`setx CONDA_HOME "C:\ProgramData\anaconda3"`
Then closing cmd windows and reopening and trying again.

**Comment by dancost** [comment]
> I was able to fix this with this in an admin cmd: `setx CONDA_HOME "C:\ProgramData\anaconda3"` Then closing all cmd windows and reopening and trying again.

I think you are confusing CONDA_HOME with CUDA_HOME. The issue here, as stated in the error, is that CUDA_HOME is not set.
