### ISSUE TITLE
Launching throws error with Exllamav2 stating "Tokenizers" are not found

### ISSUE THREAD

**Issue by Adzeiros** [turboderp/exui#47]
Followed the install instructions, launching the server.py in exui throws the below error:

```Traceback (most recent call last):
  File "G:\_AI\exui\server.py", line 11, in <module>
    from backend.models import update_model, load_models, get_model_info, list_models, remove_model, load_model, unload_model, get_loaded_model
  File "G:\_AI\exui\backend\models.py", line 5, in <module>
    from exllamav2 import(
  File "C:\Users\Adzei\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\__init__.py", line 9, in <module>
    from exllamav2.tokenizer.tokenizer import ExLlamaV2Tokenizer
  File "C:\Users\Adzei\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\tokenizer\__init__.py", line 5, in <module>
    from exllamav2.tokenizer.hf import ExLlamaV2TokenizerHF
  File "C:\Users\Adzei\AppData\Local\Programs\Python\Python310\lib\site-packages\exllamav2\tokenizer\hf.py", line 4, in <module>
    from tokenizers import Tokenizer
ModuleNotFoundError: No module named 'tokenizers'```

**Comment by SirTurlock** [comment]
Workaround is to install the "tokenizers" package which does not seem to be included in the provided requirements.txt So just do a `pip install tokenizers` in your venv.

**Comment by Zueuk** [comment]
Better error messages would indeed help! I was getting a "data did not match any variant of untagged enum" error, took some time to figure out that it was complaining about tokenizer.json
Good thing I remembered this issue, `pip install --upgrade tokenizers` fixed the problem for me
