### ISSUE TITLE
Colab installion failed

### ISSUE THREAD

**Issue by RecoveredApparatus** [turboderp/exui#7]
-- User dir: ~/exui
Traceback (most recent call last):
  File "/content/exui/server.py", line 313, in <module>
    serve(app, host = host, port = port, threads = 8)
  File "/usr/local/lib/python3.10/dist-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.10/dist-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.10/dist-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Cannot assign requested address

**Comment by turboderp** [comment]
The default endpoint is localhost, port 5000. You may not be able to bind that in Colab? Not sure. But you could try running it with `-host 127.0.0.1:5000` instead.

**Comment by RecoveredApparatus** [comment]
thanks got it working
